### ISSUE TITLE
Are the cameras synchronized?

### ISSUE THREAD

**Issue by axjensen** [NVIDIA-AI-IOT/jetson-stereo-depth#2]
Hi,
I am wondering if the cameras are synchronized? 
Am I missing something here or are the two images just taken as close as possible in time?

**Comment by Peter-Yao-7** [comment]
> 

Hey Axjensen, I was wondering if you were able to have both the C++ and python implementations to work?

**Comment by axjensen** [comment]
Hi @Peter-Yao-7 

I was able to run your C++ example. 
The python example crashes with a core dump.
Can you share some insights on the synchronization of the cameras?

Thanks

**Comment by Peter-Yao-7** [comment]
Hi @axjensen,

I'm not the owner of the repo but I was attempting to see the performance of the result too, I think the opencv python file results in a core dump but I haven't figured out why; the vpi file works but it doesn't have the same performance as shown. From what I can see, the cameras are not likely perfectly synchronized, but depending on the frame rate, they should be extremely close in time.

**Comment by tomasz-lewicki** [comment]
Hi @axjensen,

You're correct - the frames from sensors are not synced, and the code just grabs the newest available frame. Unfortunately I don't believe IMX219 camera has an option for an external trigger signal. 

Regarding the crash, please try running this before running the program:
```shell
export OPENBLAS_CORETYPE=ARMV8;
```
[Here's](https://github.com/numpy/numpy/issues/18131) more on the related issue.

**Comment by tomasz-lewicki** [comment]
@Peter-Yao-7,

Feel free to open a separate issue, I'd be happy to help camera calibration.
